services:
  php:
    container_name: ${PHP_NAME}
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - ./php/php-ini-override.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      - backend
    
  apache:
    container_name: ${APACHE_NAME}
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    networks:
      - frontend
      - backend
    ports:
      - "${HTTP_PORT}:80"
      - "${FTP_PORT}:21"
      - "${DEBUG_PORT}:9001"
    depends_on:
      - php
      - mariadb

  mariadb:
    container_name: ${MARIA_DB_NAME}
    image: mariadb:${MARIA_DB_VERSION:-latest}
    volumes:
      - data:/var/lib/mariadb
    networks:
      - backend
    ports:
      - "${MARIA_DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  composer:
    container_name: ${COMPOSER_NAME}
    image: composer:latest
    volumes:
      - ./src:/app
    working_dir: /app
    entrypoint: ["composer"]

networks:
  frontend:
  backend:
    name: ${NETWORK_NAME}
volumes:
    data: